my_app_user:
    resource: "@MyAppUserBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
my_app_graphe:
    resource: "@MyAppGrapheBundle/Resources/config/routing.yml"
    prefix:   /Graphe
